version: "3.8"

services:
  api:
    container_name: service-api
    build:
      context: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public"
    depends_on:
      cache:
        condition: service_started
      database:
        condition: service_healthy

  cache:
    container_name: service-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    volumes: 
      - ${CACHE_VOLUME:-cache_data}:/data

  database:
    container_name: service-database
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DATABASE_VOLUME:-pg_data}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
